- name: Install caSnooper
  include_role: 
    name: ansible-role-epics-base
    tasks_from: extension_common
  with_items:
    - "{{ epics_casnooper_extension }}"
  loop_control:
    loop_var: extension
